batch_size: 8
epochs: 20
hidden_dim: 16
learning_rate: 0.001
num_workers: 5
output_model_dir: ./vctk_wavlm_cont_disc_mhubert_cont/
save_model: true
weight_decay: 0.001

cont_files:
- vctk_wavlm_large_cont.pkl
- vctk_mhubert_cont.pkl

disc_files:
- vctk_wavlm_large_disc_L6.pkl
- vctk_wavlm_large_disc_L7.pkl
- vctk_wavlm_large_disc_L24.pkl
- vctk_mhubert_disc_L11.pkl

annotation_file: VCTK-Corpus-0.92/VCTK_dataset_partitions_2023.csv